id: f90f6b65ce93429ab6c4fecc0091847d
initial_creation_type: ocr
source_metadata:
  volumes:
    37a836605bc14cbfbf303357af3e3a30:
      base_file: v004.txt
      image_group_id: I1PD95849
      title: ''
      total_pages: 1678
      volume_number: 4
